<?php
// Automatically Generated by TestLink Installer - Thu, 21 Mar 19 15:51:27 +0800
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'casa1234');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
