<?php
// Automatically Generated by TestLink Installer - Wed, 15 May 19 22:22:07 -0400
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'casa1234');
define('DB_HOST', '192.168.157.91');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
